[package]
name = "imgui-wgpu"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
wgpu = { version = "0.14" }
# imgui = { git = "https://github.com/imgui-rs/imgui-rs" }
imgui = "0.11.0"
ahash = "0.8"
